version: "3.8"

services:
    fast-api:
        env_file:
            - .env
        ports:
            - "8000:80"
        build:
            context: .
            dockerfile: ./Docker/FastAPI/Dockerfile
        container_name: FastAPI
        volumes:
            - ./app:/app
            - ./app/bot:/app/bot
        networks:
            - pycab-app-network

networks:
  pycab-app-network: