version: "3.8"

services:
    fast-api:
        env_file:
            - .env
        ports:
            - "8001:8001"
        build:
            context: .
            dockerfile: ./Docker/FastAPI/Dockerfile
        container_name: FastAPI
        restart: always
        volumes:
            - ./app:/app
        networks:
            - pycab-app-network

networks:
  pycab-app-network: